### ISSUE TITLE
Clear Field

### ISSUE THREAD

**Issue by MustafaAndroid** [amlashi-sadra/AwesomeSpinner#12]
How to Clear the text Field in spinner..??

**Comment by sadra** [comment]
> How to Clear the text Field in spinner..??

Do you mean that you want clear the selection?

**Comment by MustafaAndroid** [comment]
yes there is button to clear my Edit Text Field  and spinner so if user click button all field will be clear expect spinner..??

**Comment by sadra** [comment]
> yes there is button to clear my Edit Text Field and spinner so if user click button all field will be clear expect spinner..??

ok, let me add this feature 🤗

**Comment by sadra** [comment]
> How to Clear the text Field in spinner..??

Now update the library to new version `1.4.0`  and then you can clear the selection with calling `clearSelection();` method.
