### ISSUE TITLE
Default Value

### ISSUE THREAD

**Issue by MustafaAndroid** [amlashi-sadra/AwesomeSpinner#13]
How can we set dynamic value to show in hint place ..???

**Comment by sadra** [comment]
> How can we set dynamic value to show in hint place ..???

You can change spinner hint text with call `setSpinnerHint(TEXT)` method, every time you want.

**Comment by MustafaAndroid** [comment]
setSpinnerHint is not showing.?? i update the library to 1.4.0 (Thanks for your update clearSelection)

**Comment by sadra** [comment]
Oh sorry, i forget to mention update it to the lates version, now the lates is 1.5.0.😅

**Comment by MustafaAndroid** [comment]
its not working I'm giving hardcore text but its not showing..??

**Comment by sadra** [comment]
Did you use `setSpinnerHint("Your hint title")` method?

**Comment by MustafaAndroid** [comment]
yeah i have set like this   spinnerLTR.setSpinnerHint(status) but its not showing bro..

**Comment by sadra** [comment]
Now update it to the latest version and enjoy 🤗
