### ISSUE TITLE
i got an extra arrow sign

### ISSUE THREAD

**Issue by pavelsust** [amlashi-sadra/AwesomeSpinner#18]
![device-2019-07-21-143125](https://user-images.githubusercontent.com/7562445/61588872-3bfeba00-abc4-11e9-9b3b-abf30def9d95.png)

**Comment by mehdirouhandeh** [comment]
me too..is there anyone to answer us..?

**Comment by pavelsust** [comment]
but i used this one of my another project at that time it works great

**Comment by sadra** [comment]
That's strange! 🧐
Can you tell me what's the android version of your emulator?
@mehdirouhandeh @paveltech

**Comment by mehdirouhandeh** [comment]
It's android 9, Api 29

**Comment by achinverma** [comment]
i am also getting this same error in android 9, any suggestion to fix this

**Comment by josephvijayandroiddev** [comment]
change the spinner that is better idea

**Comment by sadra** [comment]
Let me fix it today 🤦‍♂️️

**Comment by josephvijayandroiddev** [comment]
are you fix that issue sir..?

**Comment by achinverma** [comment]
> Let me fix it today ️

have you fixed it?

**Comment by josephvijayandroiddev** [comment]
> Let me fix it today 🤦‍♂️️

bro are you finish it..????

**Comment by pavelsust** [comment]
did you fix it???

**Comment by sadra** [comment]
Fix at https://github.com/sadra/AwesomeSpinner/commit/ac4a2aa08e5d6c80f2f62bf4108d2a2abcc6edca
Please update your library to `com.github.sadra:AwesomeSpinner:1.5.2`
