### ISSUE TITLE
question

### ISSUE THREAD

**Issue by alirezaashrafi** [amlashi-sadra/AwesomeSpinner#2]
دادا مگه auto complete text view همین کارو نمیکنه؟

**Comment by sadra** [comment]
سلام. ماهیت این دو باهم فرق میکنه.
Auto text complete: برای اینه که کاربر یه چیزیو تایپ کنه و به نتیجه مورد نظرش از بین گزینه‌های زیاد برسه. مصرف و فلسفه‌ش برای سرچ هست
اما Spinner: برای اینه که کاربر از بین گزینه‌های موجود و محدود یکی رو انتخاب کنه. قرار نیست کیبورد براش باز بشه و شروع کنه به تایپ کردن.
**درواقع برمی‌گرده به مفاهیم دیزاین که هدف یکی جست‌جوعه بین گزینه‌های نامحدود و دیگری انتخاب بین گزینه‌های محدود.**
