### ISSUE TITLE
setEnabled doesn't work

### ISSUE THREAD

**Issue by keskin** [amlashi-sadra/AwesomeSpinner#4]
Hello
setEnable(false) doesn't disable the spinner. any thoughts?

**Comment by sadra** [comment]
The issue was solved.
Please update the library to [`1.1.0`](https://github.com/sadra/AwesomeSpinner/releases/tag/1.1.0) version.
You can use `setSpinnerEnable` method for enabling/disabling it, and with `isSpinnerEnable` you can check it is enable or not.
