### ISSUE TITLE
custom spinner_Item

### ISSUE THREAD

**Issue by mrmosi13** [amlashi-sadra/AwesomeSpinner#5]
سلام

برا استفاده از لایوت کاستوم خودمون طبق آموزش ها باید این قطعه کد استفاده بشه 
` ArrayAdapter <CharSequence> provincesAdapter = ArrayAdapter.createFromResource(getActivity(), R.array.Month_array, R.layout.spinner_item);
        provincesAdapter.setDropDownViewResource(R.layout.spinner_item);`

ولی با استفاده از این اسپینر نمیره از اون لایوتی که آدرس میدم استفاده کنه و فقط آرایه رو میره استفاده میکنه .

ممنون میشم راهنماییم کنین مشکل از کجاست 

مرسی

**Comment by AmirNorouzpour** [comment]
منم همین مشکلو دارم 
فکر میکنم layout که معرفی میکنم اونو ست نمیکنه .
میخوام با layout مشکل فونت فارسی رو حل کنم، یعنی تو layout ی فونت فارسی گذاشتم، اما نمیره از اون بخونه!

**Comment by sadra** [comment]
> منم همین مشکلو دارم
> فکر میکنم layout که معرفی میکنم اونو ست نمیکنه .
> میخوام با layout مشکل فونت فارسی رو حل کنم، یعنی تو layout ی فونت فارسی گذاشتم، اما نمیره از اون بخونه!



> سلام
> 
> برا استفاده از لایوت کاستوم خودمون طبق آموزش ها باید این قطعه کد استفاده بشه
> ` ArrayAdapter <CharSequence> provincesAdapter = ArrayAdapter.createFromResource(getActivity(), R.array.Month_array, R.layout.spinner_item); provincesAdapter.setDropDownViewResource(R.layout.spinner_item);`
> 
> ولی با استفاده از این اسپینر نمیره از اون لایوتی که آدرس میدم استفاده کنه و فقط آرایه رو میره استفاده میکنه .
> 
> ممنون میشم راهنماییم کنین مشکل از کجاست
> 
> مرسی

Let me check the problem. thank you

**Comment by sadra** [comment]
> منم همین مشکلو دارم
> فکر میکنم layout که معرفی میکنم اونو ست نمیکنه .
> میخوام با layout مشکل فونت فارسی رو حل کنم، یعنی تو layout ی فونت فارسی گذاشتم، اما نمیره از اون بخونه!



> سلام
> 
> برا استفاده از لایوت کاستوم خودمون طبق آموزش ها باید این قطعه کد استفاده بشه
> ` ArrayAdapter <CharSequence> provincesAdapter = ArrayAdapter.createFromResource(getActivity(), R.array.Month_array, R.layout.spinner_item); provincesAdapter.setDropDownViewResource(R.layout.spinner_item);`
> 
> ولی با استفاده از این اسپینر نمیره از اون لایوتی که آدرس میدم استفاده کنه و فقط آرایه رو میره استفاده میکنه .
> 
> ممنون میشم راهنماییم کنین مشکل از کجاست
> 
> مرسی

You should pass your `viewResource` throw the following method:

```
awesomeSpinner.setDropDownViewResource(R.layout.my_sample_spinner_item);
```

**Comment by AmirNorouzpour** [comment]
ممنون از راهنمایی شما،
فقط ی سوال آیتم انتخاب شده یعنی متن که نمایش داده میشه فونت نمیشه داد بهش یا layout بهش داد؟

**Comment by sadra** [comment]
> ممنون از راهنمایی شما،
> فقط ی سوال آیتم انتخاب شده یعنی متن که نمایش داده میشه فونت نمیشه داد بهش یا layout بهش داد؟

You can use this library to set font [https://github.com/chrisjenx/Calligraphy](https://github.com/chrisjenx/Calligraphy)
But if your minimum version support is more than `API 21` you can set the font in `xml` file, check this topic [https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml](https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml)
