### ISSUE TITLE
Hint color and arrow color

### ISSUE THREAD

**Issue by emmanuel0027** [amlashi-sadra/AwesomeSpinner#8]
I cant set the hint color and arrow color, this features would be awesome

**Comment by sadra** [comment]
The features added:
Add `setSelectedItemHintColor` to change **Selected Item Hint** color.
Add `setDownArrowTintColor` to change **Down Arrow** color.

Check the [Documentation](https://github.com/sadra/AwesomeSpinner#additional-controls) and update the library to the new version 🤗

**Comment by emmanuel0027** [comment]
Thanks!
You are awesome ;)

**Comment by sadra** [comment]
#10
